import builtins from "builtin-modules";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import { optimize } from "svgo";

import "dotenv/config";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv.includes("production");
const sync = process.argv.includes("sync");

/** @type import('esbuild').Plugin */
let syncOsePlugin = {
  name: "sync-ose-plugin",
  setup(build) {
    if (!process.env.SYNC_DESTINATION)
      throw Error("process.env.SYNC_DESTINATION not set");

    build.onEnd(() => {
      for (const src of [
        "main.js",
        "manifest.json",
        "styles.css",
        "versions.json",
      ]) {
        const dst = path.join(process.env.SYNC_DESTINATION, src);
        fs.copyFileSync(src, dst);
        console.log(`copied ${src} to ${dst}`);
      }
    });
  },
};

const svgTagPattern = /<svg [^>]+>(.*)<\/svg>/;

/**
 * @param {string} str
 * @returns {string}
 */
function stripSvgTag(str) {
  const matches = str.match(svgTagPattern);
  return matches ? matches[0] : str;
}

/** @type import('esbuild').Plugin */
let svgProcessPlugin = {
  name: "svg-process-plugin",
  setup(build) {
    build.onLoad({ filter: /\.svg$/ }, (args) => {
      const contents = fs.readFileSync(args.path, { encoding: "utf-8" });
      return {
        contents: stripSvgTag(optimize(contents).data),
        loader: "text",
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [svgProcessPlugin].concat(sync ? [syncOsePlugin] : []),
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
